version: "3.8" # https://docs.docker.com/compose/compose-file/

services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    hostname: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.entrypoints=web"
      - "traefik.http.routers.portainer.rule=Host(`portainer.$MY_DOMAIN`)"
    # environment: # https://docs.docker.com/compose/environment-variables/
    deploy:
      resources:
        limits:
          cpus: '2'
          cpu_shares: 1024


networks:
  default:
    external:
      name: $DEFAULT_NETWORK

volumes:
  portainer_data:
