## traefik.yml

# Docker configuration backend
providers:
  docker:
    #defaultRule: "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.docker.d01`)"

# API and dashboard configuration
api:
  insecure: true
  
